name: towerdefense
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffi: ^2.1.4
  flame: ^1.34.0
  flame_audio: ^2.11.12
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/img/Tower Defense.png
  adaptive_icon_foreground: assets/img/Tower Defense.png
  adaptive_icon_background: "#00000000"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/data/maps.js
    - assets/audio/
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
