#include "TowerCatalog.h"

namespace towerdefense {

namespace {

// Balance source of truth. Cost roughly tracks DPS x range; each upgrade is strictly
// stronger and never regresses damage (enforced by validateContent at startup).
// Field order: kind, kindId, title, cost, damageMin, damageMax, range,
//   cooldownMin, cooldownMax, damageTypeLabel, effectText, displayColor,
//   storeVisible, targetingText, nextUpgradeKind, nextUpgradeKindId, [statusOnly].
constexpr std::array<TowerCatalogEntry, 20> kTowerCatalogEntries = {{
    {
        TowerKindId::Gun,
        "gun",
        "Gun Tower",
        25,
        8.0f,
        18.0f,
        3.0f,
        8,
        18,
        "PHYSICAL",
        "Light autocannon with reliable kinetic fire",
        0xFF567060,
        true,
        "Targets the leading enemy",
        TowerKindId::MachineGun,
        "machineGun",
    },
    {
        TowerKindId::MachineGun,
        "machineGun",
        "Machine Gun",
        60,
        4.0f,
        10.0f,
        3.0f,
        3,
        5,
        "PHYSICAL",
        "High-rate cannon with sustained suppressive fire",
        0xFF56767E,
        false,
        "Targets the leading enemy",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Laser,
        "laser",
        "Laser Tower",
        75,
        6.0f,
        10.0f,
        2.5f,
        2,
        3,
        "ENERGY",
        "Directed-energy turret for close defense",
        0xFF787853,
        true,
        "Targets the leading enemy",
        TowerKindId::BeamEmitter,
        "beamEmitter",
    },
    {
        TowerKindId::BeamEmitter,
        "beamEmitter",
        "Beam Emitter",
        180,
        8.0f,
        14.0f,
        3.0f,
        1,
        2,
        "ENERGY",
        "Beam dwell time compounds thermal damage",
        0xFF959B6B,
        false,
        "Targets the leading enemy",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Slow,
        "slow",
        "Slow Tower",
        100,
        0.0f,
        0.0f,
        2.5f,
        0,
        0,
        "SLOW",
        "Area denial emitter disrupts enemy movement",
        0xFF606E62,
        true,
        "Affects all enemies in range",
        TowerKindId::Poison,
        "poison",
        true,
    },
    {
        TowerKindId::Poison,
        "poison",
        "Poison Tower",
        150,
        0.0f,
        0.0f,
        2.5f,
        60,
        60,
        "POISON",
        "Chemical dispersal damages targets over time",
        0xFF568072,
        false,
        "Affects all enemies in range",
        TowerKindId::Unknown,
        "",
        true,
    },
    {
        TowerKindId::Sniper,
        "sniper",
        "Sniper Tower",
        150,
        90.0f,
        110.0f,
        9.0f,
        60,
        100,
        "PHYSICAL",
        "Long-range anti-materiel rifle",
        0xFF5A666C,
        true,
        "Targets the strongest visible enemy",
        TowerKindId::Railgun,
        "railgun",
    },
    {
        TowerKindId::Railgun,
        "railgun",
        "Railgun",
        300,
        180.0f,
        220.0f,
        11.0f,
        100,
        120,
        "PIERCING",
        "Electromagnetic slug impacts nearby armored targets",
        0xFF665A55,
        false,
        "Targets the strongest visible enemy",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Rocket,
        "rocket",
        "Rocket Tower",
        200,
        40.0f,
        60.0f,
        7.0f,
        60,
        80,
        "EXPLOSION",
        "Guided micro-missiles with blast damage",
        0xFF52725E,
        true,
        "Targets the nearest valid enemy within range",
        TowerKindId::MissileSilo,
        "missileSilo",
    },
    {
        TowerKindId::MissileSilo,
        "missileSilo",
        "Missile Silo",
        380,
        90.0f,
        120.0f,
        9.0f,
        60,
        80,
        "EXPLOSION",
        "Heavier missiles with larger shaped blasts",
        0xFF8A7E70,
        false,
        "Targets the nearest valid enemy within range",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Bomb,
        "bomb",
        "Bomb Tower",
        175,
        20.0f,
        60.0f,
        2.0f,
        40,
        60,
        "EXPLOSION",
        "Short-range mortar with fragmentation blast",
        0xFF526167,
        true,
        "Targets the leading enemy",
        TowerKindId::ClusterBomb,
        "clusterBomb",
    },
    {
        TowerKindId::ClusterBomb,
        "clusterBomb",
        "Cluster Bomb",
        320,
        70.0f,
        110.0f,
        2.5f,
        40,
        80,
        "EXPLOSION",
        "Splits into multiple secondary explosions",
        0xFF616752,
        false,
        "Targets the leading enemy",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Tesla,
        "tesla",
        "Tesla Coil",
        350,
        200.0f,
        320.0f,
        4.0f,
        60,
        80,
        "ENERGY",
        "Prototype coil discharge chaining through nearby targets",
        0xFFC6BCA8,
        true,
        "Targets the leading enemy, then chains",
        TowerKindId::Plasma,
        "plasma",
    },
    {
        TowerKindId::Plasma,
        "plasma",
        "Plasma Tower",
        600,
        400.0f,
        600.0f,
        4.5f,
        40,
        60,
        "ENERGY",
        "Higher-output plasma discharge with faster recovery",
        0xFFD6C68E,
        false,
        "Targets the leading enemy, then chains",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Gatling,
        "gatling",
        "Gatling Turret",
        90,
        3.0f,
        6.0f,
        3.5f,
        2,
        3,
        "PHYSICAL",
        "Rotary autocannon shredding light targets at high rate",
        0xFF6E7A52,
        true,
        "Targets the leading enemy",
        TowerKindId::VulcanCiws,
        "vulcanCiws",
    },
    {
        TowerKindId::VulcanCiws,
        "vulcanCiws",
        "Vulcan CIWS",
        200,
        5.0f,
        9.0f,
        3.5f,
        1,
        2,
        "PHYSICAL",
        "Close-in weapon system: a wall of rotary cannon fire",
        0xFF8A9466,
        false,
        "Targets the leading enemy",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Mortar,
        "mortar",
        "Mortar Battery",
        220,
        50.0f,
        80.0f,
        8.0f,
        70,
        90,
        "EXPLOSION",
        "Lobs arcing shells onto distant targets with wide splash",
        0xFF6B6552,
        true,
        "Targets the nearest valid enemy within range",
        TowerKindId::SiegeHowitzer,
        "siegeHowitzer",
    },
    {
        TowerKindId::SiegeHowitzer,
        "siegeHowitzer",
        "Siege Howitzer",
        420,
        110.0f,
        150.0f,
        10.0f,
        70,
        90,
        "EXPLOSION",
        "Heavy artillery: devastating arcing barrages",
        0xFF8A7E66,
        false,
        "Targets the nearest valid enemy within range",
        TowerKindId::Unknown,
        "",
    },
    {
        TowerKindId::Interceptor,
        "interceptor",
        "SAM Interceptor",
        240,
        60.0f,
        90.0f,
        9.0f,
        50,
        70,
        "EXPLOSION",
        "Fast guided interceptors that lead and run down targets",
        0xFF52727E,
        true,
        "Targets the nearest valid enemy within range",
        TowerKindId::AegisBattery,
        "aegisBattery",
    },
    {
        TowerKindId::AegisBattery,
        "aegisBattery",
        "Aegis Battery",
        460,
        120.0f,
        170.0f,
        11.0f,
        45,
        65,
        "EXPLOSION",
        "Layered air-defense salvos with rapid reload",
        0xFF6688A0,
        false,
        "Targets the nearest valid enemy within range",
        TowerKindId::Unknown,
        "",
    },
}};

}  // namespace

const std::array<TowerCatalogEntry, 20> &towerCatalogEntries() {
    return kTowerCatalogEntries;
}

const TowerCatalogEntry *findTowerCatalogEntry(std::string_view kindId) {
    for (const TowerCatalogEntry &entry : kTowerCatalogEntries) {
        if (entry.kindId == kindId) {
            return &entry;
        }
    }
    return nullptr;
}

const TowerCatalogEntry *findTowerCatalogEntry(TowerKindId kindId) {
    for (const TowerCatalogEntry &entry : kTowerCatalogEntries) {
        if (entry.kind == kindId) {
            return &entry;
        }
    }
    return nullptr;
}

const TowerCatalogEntry *findNextTowerUpgrade(std::string_view kindId) {
    const TowerCatalogEntry *entry = findTowerCatalogEntry(kindId);
    if (entry == nullptr || entry->nextUpgradeKindId.empty()) {
        return nullptr;
    }
    return findTowerCatalogEntry(entry->nextUpgradeKindId);
}

const TowerCatalogEntry *findNextTowerUpgrade(TowerKindId kindId) {
    const TowerCatalogEntry *entry = findTowerCatalogEntry(kindId);
    if (entry == nullptr || entry->nextUpgradeKind == TowerKindId::Unknown) {
        return nullptr;
    }
    return findTowerCatalogEntry(entry->nextUpgradeKind);
}

}  // namespace towerdefense
