import 'package:flutter/material.dart';

import 'models.dart';

const mapsAssetPath = 'assets/data/maps.js';
const soundAssetRoot = 'assets/audio/';

String soundAsset(String fileName) => '$soundAssetRoot$fileName';

const authoredMapNames = <String>{
  'loops',
  'spiral',
  'branch',
  'branchAlt',
  'city',
  'freeway',
  'walls',
  'fork',
};

const proceduralMapNames = <String>{
  'empty2',
  'empty3',
  'sparse2',
  'sparse3',
  'dense2',
  'dense3',
  'solid2',
  'solid3',
};

const selectableMapNames = <String>[
  'empty2',
  'empty3',
  'sparse2',
  'sparse3',
  'dense2',
  'dense3',
  'solid2',
  'solid3',
  'loops',
  'spiral',
  'branch',
  'branchAlt',
  'city',
  'freeway',
  'walls',
  'fork',
];

const mapLabels = <String, String>{
  'empty2': 'Empty (2)',
  'empty3': 'Empty (3)',
  'sparse2': 'Sparse (2)',
  'sparse3': 'Sparse (3)',
  'dense2': 'Dense (2)',
  'dense3': 'Dense (3)',
  'solid2': 'Solid (2)',
  'solid3': 'Solid (3)',
  'loops': 'Loops',
  'spiral': 'Spiral',
  'branch': 'Branch',
  'branchAlt': 'Branch (Alt)',
  'city': 'City',
  'freeway': 'Freeway',
  'walls': 'Walls',
  'fork': 'Fork',
};

const difficultyLabels = <Difficulty, String>{
  Difficulty.relaxed: 'Relaxed',
  Difficulty.normal: 'Normal',
  Difficulty.hard: 'Hard',
};

const waveModeLabels = <WaveMode, String>{
  WaveMode.endless: 'Endless',
  WaveMode.preset: 'Preset Waves',
  WaveMode.custom: 'Custom Waves',
};

EnemyKind enemyKindFromName(String name) {
  return EnemyKind.values.firstWhere((kind) => kind.name == name);
}

const effectBlueprints = <EffectKind, EffectBlueprint>{
  EffectKind.slow: EffectBlueprint(
    kind: EffectKind.slow,
    color: Color(0xFF446CB3),
  ),
  EffectKind.poison: EffectBlueprint(
    kind: EffectKind.poison,
    color: Color(0xFF66CC1A),
  ),
  EffectKind.regen: EffectBlueprint(
    kind: EffectKind.regen,
    color: Color(0xFFD2527F),
  ),
};

const towerBlueprints = <TowerKind, TowerBlueprint>{
  TowerKind.gun: TowerBlueprint(
    kind: TowerKind.gun,
    title: 'Gun Tower',
    effectText: 'Light autocannon with reliable kinetic fire',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.physical,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.first,
    cost: 25,
    range: 3,
    damageMin: 8,
    damageMax: 18,
    cooldownMin: 8,
    cooldownMax: 18,
    color: Color(0xFF607056),
    secondaryColor: Color(0xFF80887E),
    flashColor: Color(0xFFFFD492),
    radius: 0.9,
    length: 0.65,
    width: 0.3,
    weight: 2,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [TowerKind.machineGun],
  ),
  TowerKind.machineGun: TowerBlueprint(
    kind: TowerKind.machineGun,
    title: 'Machine Gun',
    effectText: 'High-rate cannon with sustained suppressive fire',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.physical,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.first,
    cost: 60,
    range: 3,
    damageMin: 4,
    damageMax: 10,
    cooldownMin: 3,
    cooldownMax: 5,
    color: Color(0xFF7E7656),
    secondaryColor: Color(0xFF80887E),
    flashColor: Color(0xFFFFBF80),
    radius: 0.9,
    length: 0.65,
    width: 0.3,
    weight: 2,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [],
  ),
  TowerKind.laser: TowerBlueprint(
    kind: TowerKind.laser,
    title: 'Laser Tower',
    effectText: 'Directed-energy turret for close defense',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.energy,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.first,
    cost: 75,
    range: 2.5,
    damageMin: 6,
    damageMax: 10,
    cooldownMin: 2,
    cooldownMax: 3,
    color: Color(0xFF537875),
    secondaryColor: Color(0xFF80887E),
    flashColor: Color(0xFF9CDCD6),
    radius: 0.8,
    length: 0.55,
    width: 0.25,
    weight: 2,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [TowerKind.beamEmitter],
  ),
  TowerKind.beamEmitter: TowerBlueprint(
    kind: TowerKind.beamEmitter,
    title: 'Beam Emitter',
    effectText: 'Beam dwell time compounds thermal damage',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.energy,
    behavior: TowerBehavior.beam,
    targetingMode: TargetingMode.first,
    cost: 180,
    range: 3,
    damageMin: 8,
    damageMax: 14,
    cooldownMin: 1,
    cooldownMax: 2,
    color: Color(0xFF6B9B95),
    secondaryColor: Color(0xFF9CA09A),
    flashColor: Color(0xFF9CDCD6),
    radius: 0.9,
    length: 0.65,
    width: 0.35,
    weight: 3,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [],
  ),
  TowerKind.slow: TowerBlueprint(
    kind: TowerKind.slow,
    title: 'Slow Tower',
    effectText: 'Area denial emitter disrupts enemy movement',
    targetingText: 'Affects all enemies in range',
    damageType: DamageType.slow,
    behavior: TowerBehavior.areaStatus,
    targetingMode: TargetingMode.area,
    cost: 100,
    range: 2.5,
    damageMin: 0,
    damageMax: 0,
    cooldownMin: 0,
    cooldownMax: 0,
    color: Color(0xFF626E60),
    secondaryColor: Color(0xFF879184),
    flashColor: Color(0xFFFFD492),
    radius: 0.9,
    length: 1.1,
    width: 0.3,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [TowerKind.poison],
  ),
  TowerKind.poison: TowerBlueprint(
    kind: TowerKind.poison,
    title: 'Poison Tower',
    effectText: 'Chemical dispersal damages targets over time',
    targetingText: 'Affects all enemies in range',
    damageType: DamageType.poison,
    behavior: TowerBehavior.areaStatus,
    targetingMode: TargetingMode.area,
    cost: 150,
    range: 2.5,
    damageMin: 0,
    damageMax: 0,
    cooldownMin: 60,
    cooldownMax: 60,
    color: Color(0xFF728056),
    secondaryColor: Color(0xFF879184),
    flashColor: Color(0xFFFFD492),
    radius: 0.9,
    length: 1.1,
    width: 0.3,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [],
  ),
  TowerKind.sniper: TowerBlueprint(
    kind: TowerKind.sniper,
    title: 'Sniper Tower',
    effectText: 'Long-range anti-materiel rifle',
    targetingText: 'Targets the strongest visible enemy',
    damageType: DamageType.physical,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.strongest,
    cost: 150,
    range: 9,
    damageMin: 90,
    damageMax: 110,
    cooldownMin: 60,
    cooldownMax: 100,
    color: Color(0xFF6C665A),
    secondaryColor: Color(0xFF6C665A),
    flashColor: Color(0xFFFFE0B8),
    radius: 0.9,
    length: 0.7,
    width: 0.3,
    weight: 3,
    baseOnTop: true,
    hasBase: false,
    hasBarrel: true,
    drawLine: true,
    follow: false,
    recoilAmount: 0.16,
    sound: 'sniper.wav',
    upgrades: [TowerKind.railgun],
  ),
  TowerKind.railgun: TowerBlueprint(
    kind: TowerKind.railgun,
    title: 'Railgun',
    effectText: 'Electromagnetic slug impacts nearby armored targets',
    targetingText: 'Targets the strongest visible enemy',
    damageType: DamageType.piercing,
    behavior: TowerBehavior.splashOnHit,
    targetingMode: TargetingMode.strongest,
    cost: 300,
    range: 11,
    damageMin: 180,
    damageMax: 220,
    cooldownMin: 100,
    cooldownMax: 120,
    color: Color(0xFF555A66),
    secondaryColor: Color(0xFF76808C),
    flashColor: Color(0xFFFFE0B8),
    radius: 1,
    length: 0.7,
    width: 0.4,
    weight: 4,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: false,
    recoilAmount: 0.16,
    sound: 'railgun.wav',
    upgrades: [],
  ),
  TowerKind.rocket: TowerBlueprint(
    kind: TowerKind.rocket,
    title: 'Rocket Tower',
    effectText: 'Guided micro-missiles with blast damage',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missile,
    targetingMode: TargetingMode.nearest,
    cost: 200,
    range: 7,
    damageMin: 40,
    damageMax: 60,
    cooldownMin: 60,
    cooldownMax: 80,
    color: Color(0xFF5E7252),
    secondaryColor: Color(0xFF82887E),
    flashColor: Color(0xFFFFD492),
    radius: 0.75,
    length: 0.6,
    width: 0.2,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'missile.wav',
    upgrades: [TowerKind.missileSilo],
  ),
  TowerKind.missileSilo: TowerBlueprint(
    kind: TowerKind.missileSilo,
    title: 'Missile Silo',
    effectText: 'Heavier missiles with larger shaped blasts',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missileSilo,
    targetingMode: TargetingMode.nearest,
    cost: 380,
    range: 9,
    damageMin: 90,
    damageMax: 120,
    cooldownMin: 60,
    cooldownMax: 80,
    color: Color(0xFF70808A),
    secondaryColor: Color(0xFF626C73),
    flashColor: Color(0xFFFFD492),
    radius: 0.75,
    length: 0.6,
    width: 0.2,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'missile.wav',
    upgrades: [],
  ),
  TowerKind.bomb: TowerBlueprint(
    kind: TowerKind.bomb,
    title: 'Bomb Tower',
    effectText: 'Short-range mortar with fragmentation blast',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.splashOnHit,
    targetingMode: TargetingMode.first,
    cost: 175,
    range: 2,
    damageMin: 20,
    damageMax: 60,
    cooldownMin: 40,
    cooldownMax: 60,
    color: Color(0xFF676152),
    secondaryColor: Color(0xFF777C73),
    flashColor: Color(0xFFFFD492),
    radius: 1,
    length: 0.6,
    width: 0.35,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [TowerKind.clusterBomb],
  ),
  TowerKind.clusterBomb: TowerBlueprint(
    kind: TowerKind.clusterBomb,
    title: 'Cluster Bomb',
    effectText: 'Splits into multiple secondary explosions',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.clusterBomb,
    targetingMode: TargetingMode.first,
    cost: 320,
    range: 2.5,
    damageMin: 70,
    damageMax: 110,
    cooldownMin: 40,
    cooldownMax: 80,
    color: Color(0xFF676152),
    secondaryColor: Color(0xFF777C73),
    flashColor: Color(0xFFFFD492),
    radius: 1.1,
    length: 0.6,
    width: 0.35,
    weight: 2,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: null,
    upgrades: [],
  ),
  TowerKind.tesla: TowerBlueprint(
    kind: TowerKind.tesla,
    title: 'Tesla Coil',
    effectText: 'Prototype coil discharge chaining through nearby targets',
    targetingText: 'Targets the leading enemy, then chains',
    damageType: DamageType.energy,
    behavior: TowerBehavior.chain,
    targetingMode: TargetingMode.chain,
    cost: 350,
    range: 4,
    damageMin: 200,
    damageMax: 320,
    cooldownMin: 60,
    cooldownMax: 80,
    color: Color(0xFFA8BCC6),
    secondaryColor: Color(0xFF586C76),
    flashColor: Color(0xFFFFD492),
    radius: 1,
    length: 0.6,
    width: 0.3,
    weight: 7,
    baseOnTop: true,
    hasBase: false,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'spark.wav',
    upgrades: [TowerKind.plasma],
  ),
  TowerKind.plasma: TowerBlueprint(
    kind: TowerKind.plasma,
    title: 'Plasma Tower',
    effectText: 'Higher-output plasma discharge with faster recovery',
    targetingText: 'Targets the leading enemy, then chains',
    damageType: DamageType.energy,
    behavior: TowerBehavior.chain,
    targetingMode: TargetingMode.chain,
    cost: 600,
    range: 4.5,
    damageMin: 400,
    damageMax: 600,
    cooldownMin: 40,
    cooldownMax: 60,
    color: Color(0xFF8EC6D6),
    secondaryColor: Color(0xFF4E6670),
    flashColor: Color(0xFFFFD492),
    radius: 1.1,
    length: 0.6,
    width: 0.3,
    weight: 7,
    baseOnTop: true,
    hasBase: false,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'spark.wav',
    upgrades: [],
  ),
  TowerKind.gatling: TowerBlueprint(
    kind: TowerKind.gatling,
    title: 'Gatling Turret',
    effectText: 'Rotary autocannon shredding light targets at high rate',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.physical,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.first,
    cost: 90,
    range: 3.5,
    damageMin: 3,
    damageMax: 6,
    cooldownMin: 2,
    cooldownMax: 3,
    color: Color(0xFF6E7A52),
    secondaryColor: Color(0xFF7E8678),
    flashColor: Color(0xFFFFD692),
    radius: 0.92,
    length: 0.7,
    width: 0.34,
    weight: 3,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.12,
    sound: null,
    upgrades: [TowerKind.vulcanCiws],
  ),
  TowerKind.vulcanCiws: TowerBlueprint(
    kind: TowerKind.vulcanCiws,
    title: 'Vulcan CIWS',
    effectText: 'Close-in weapon system: a wall of rotary cannon fire',
    targetingText: 'Targets the leading enemy',
    damageType: DamageType.physical,
    behavior: TowerBehavior.direct,
    targetingMode: TargetingMode.first,
    cost: 200,
    range: 3.5,
    damageMin: 5,
    damageMax: 9,
    cooldownMin: 1,
    cooldownMax: 2,
    color: Color(0xFF8A9466),
    secondaryColor: Color(0xFF7E8678),
    flashColor: Color(0xFFFFD692),
    radius: 0.95,
    length: 0.72,
    width: 0.36,
    weight: 3,
    baseOnTop: true,
    hasBase: true,
    hasBarrel: true,
    drawLine: true,
    follow: true,
    recoilAmount: 0.12,
    sound: null,
    upgrades: [],
  ),
  TowerKind.mortar: TowerBlueprint(
    kind: TowerKind.mortar,
    title: 'Mortar Battery',
    effectText: 'Lobs arcing shells onto distant targets with wide splash',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missileSilo,
    targetingMode: TargetingMode.nearest,
    cost: 220,
    range: 8,
    damageMin: 50,
    damageMax: 80,
    cooldownMin: 70,
    cooldownMax: 90,
    color: Color(0xFF6B6552),
    secondaryColor: Color(0xFF8A7E66),
    flashColor: Color(0xFFFFD6AA),
    radius: 0.85,
    length: 0.6,
    width: 0.32,
    weight: 4,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.2,
    sound: 'missile.wav',
    upgrades: [TowerKind.siegeHowitzer],
  ),
  TowerKind.siegeHowitzer: TowerBlueprint(
    kind: TowerKind.siegeHowitzer,
    title: 'Siege Howitzer',
    effectText: 'Heavy artillery delivering devastating arcing barrages',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missileSilo,
    targetingMode: TargetingMode.nearest,
    cost: 420,
    range: 10,
    damageMin: 110,
    damageMax: 150,
    cooldownMin: 70,
    cooldownMax: 90,
    color: Color(0xFF8A7E66),
    secondaryColor: Color(0xFF6B6552),
    flashColor: Color(0xFFFFD6AA),
    radius: 0.9,
    length: 0.65,
    width: 0.34,
    weight: 4,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.2,
    sound: 'missile.wav',
    upgrades: [],
  ),
  TowerKind.interceptor: TowerBlueprint(
    kind: TowerKind.interceptor,
    title: 'SAM Interceptor',
    effectText: 'Fast guided interceptors that lead and run down targets',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missile,
    targetingMode: TargetingMode.nearest,
    cost: 240,
    range: 9,
    damageMin: 60,
    damageMax: 90,
    cooldownMin: 50,
    cooldownMax: 70,
    color: Color(0xFF52727E),
    secondaryColor: Color(0xFF668DA0),
    flashColor: Color(0xFF9CDCD6),
    radius: 0.78,
    length: 0.6,
    width: 0.22,
    weight: 3,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'missile.wav',
    upgrades: [TowerKind.aegisBattery],
  ),
  TowerKind.aegisBattery: TowerBlueprint(
    kind: TowerKind.aegisBattery,
    title: 'Aegis Battery',
    effectText: 'Layered air-defense salvos with rapid reload',
    targetingText: 'Targets the nearest valid enemy within range',
    damageType: DamageType.explosion,
    behavior: TowerBehavior.missile,
    targetingMode: TargetingMode.nearest,
    cost: 460,
    range: 11,
    damageMin: 120,
    damageMax: 170,
    cooldownMin: 45,
    cooldownMax: 65,
    color: Color(0xFF668DA0),
    secondaryColor: Color(0xFF52727E),
    flashColor: Color(0xFF9CDCD6),
    radius: 0.82,
    length: 0.62,
    width: 0.24,
    weight: 3,
    baseOnTop: false,
    hasBase: true,
    hasBarrel: true,
    drawLine: false,
    follow: true,
    recoilAmount: 0.16,
    sound: 'missile.wav',
    upgrades: [],
  ),
};

const enemyBlueprints = <EnemyKind, EnemyBlueprint>{
  EnemyKind.weak: EnemyBlueprint(
    kind: EnemyKind.weak,
    name: 'weak',
    behavior: EnemyBehavior.basic,
    color: Color(0xFF929891),
    secondaryColor: Color(0xFFBEC2B8),
    radius: 0.5,
    cash: 1,
    health: 35,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.strong: EnemyBlueprint(
    kind: EnemyKind.strong,
    name: 'strong',
    behavior: EnemyBehavior.basic,
    color: Color(0xFF60676A),
    secondaryColor: Color(0xFF919693),
    radius: 0.6,
    cash: 1,
    health: 75,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.fast: EnemyBlueprint(
    kind: EnemyKind.fast,
    name: 'fast',
    behavior: EnemyBehavior.arrowhead,
    color: Color(0xFF76848A),
    secondaryColor: Color(0xFFBEC6C4),
    radius: 0.5,
    cash: 2,
    health: 75,
    damage: 1,
    speed: 2,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.strongFast: EnemyBlueprint(
    kind: EnemyKind.strongFast,
    name: 'strongFast',
    behavior: EnemyBehavior.arrowhead,
    color: Color(0xFF566A74),
    secondaryColor: Color(0xFFAAB4B2),
    radius: 0.5,
    cash: 2,
    health: 135,
    damage: 1,
    speed: 2,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.medic: EnemyBlueprint(
    kind: EnemyKind.medic,
    name: 'medic',
    behavior: EnemyBehavior.medic,
    color: Color(0xFF7F7466),
    secondaryColor: Color(0xFFC14A3A),
    radius: 0.7,
    cash: 4,
    health: 375,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{DamageType.regen},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.stronger: EnemyBlueprint(
    kind: EnemyKind.stronger,
    name: 'stronger',
    behavior: EnemyBehavior.basic,
    color: Color(0xFF565A58),
    secondaryColor: Color(0xFF848A86),
    radius: 0.8,
    cash: 4,
    health: 375,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.faster: EnemyBlueprint(
    kind: EnemyKind.faster,
    name: 'faster',
    behavior: EnemyBehavior.arrowhead,
    color: Color(0xFF7A745C),
    secondaryColor: Color(0xFFD6A85C),
    radius: 0.5,
    cash: 4,
    health: 375,
    damage: 1,
    speed: 3,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{DamageType.explosion},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.tank: EnemyBlueprint(
    kind: EnemyKind.tank,
    name: 'tank',
    behavior: EnemyBehavior.tank,
    color: Color(0xFF5C6C52),
    secondaryColor: Color(0xFF929886),
    radius: 1,
    cash: 4,
    health: 750,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{DamageType.poison, DamageType.slow},
    resistances: <DamageType>{DamageType.energy, DamageType.physical},
    weaknesses: <DamageType>{DamageType.explosion, DamageType.piercing},
  ),
  EnemyKind.taunt: EnemyBlueprint(
    kind: EnemyKind.taunt,
    name: 'taunt',
    behavior: EnemyBehavior.taunt,
    color: Color(0xFF605670),
    secondaryColor: Color(0xFFC89C54),
    radius: 0.8,
    cash: 8,
    health: 1500,
    damage: 1,
    speed: 1,
    taunt: true,
    sound: 'taunt.wav',
    immunities: <DamageType>{DamageType.poison, DamageType.slow},
    resistances: <DamageType>{DamageType.energy, DamageType.physical},
    weaknesses: <DamageType>{},
  ),
  EnemyKind.spawner: EnemyBlueprint(
    kind: EnemyKind.spawner,
    name: 'spawner',
    behavior: EnemyBehavior.spawner,
    color: Color(0xFF888056),
    secondaryColor: Color(0xFFD6BC66),
    radius: 0.7,
    cash: 10,
    health: 1150,
    damage: 1,
    speed: 1,
    taunt: false,
    sound: 'pop.wav',
    immunities: <DamageType>{},
    resistances: <DamageType>{},
    weaknesses: <DamageType>{},
  ),
};

const presetWaves = <WaveTemplate>[
  WaveTemplate(
    spawnCooldown: 40,
    groups: [
      WaveGroup(sequence: [EnemyKind.weak], count: 20),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 30,
    groups: [
      WaveGroup(sequence: [EnemyKind.weak], count: 10),
      WaveGroup(sequence: [EnemyKind.fast], count: 10),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 20,
    groups: [
      WaveGroup(sequence: [EnemyKind.strong], count: 15),
      WaveGroup(sequence: [EnemyKind.fast], count: 10),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 20,
    groups: [
      WaveGroup(
        sequence: [EnemyKind.medic, EnemyKind.strong, EnemyKind.strong],
        count: 10,
      ),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 15,
    groups: [
      WaveGroup(sequence: [EnemyKind.strongFast], count: 20),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 15,
    groups: [
      WaveGroup(sequence: [EnemyKind.tank], count: 8),
      WaveGroup(sequence: [EnemyKind.fast], count: 16),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 10,
    groups: [
      WaveGroup(sequence: [EnemyKind.spawner], count: 2),
      WaveGroup(sequence: [EnemyKind.stronger], count: 18),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 10,
    groups: [
      WaveGroup(
        sequence: [
          EnemyKind.taunt,
          EnemyKind.tank,
          EnemyKind.tank,
          EnemyKind.stronger,
        ],
        count: 10,
      ),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 5,
    groups: [
      WaveGroup(
        sequence: [EnemyKind.taunt, EnemyKind.medic, EnemyKind.tank],
        count: 16,
      ),
      WaveGroup(sequence: [EnemyKind.faster], count: 24),
    ],
  ),
];

const defaultCustomWaves = <WaveTemplate>[
  WaveTemplate(
    spawnCooldown: 30,
    groups: [
      WaveGroup(sequence: [EnemyKind.weak], count: 12),
      WaveGroup(sequence: [EnemyKind.strong], count: 6),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 20,
    groups: [
      WaveGroup(sequence: [EnemyKind.fast], count: 14),
      WaveGroup(sequence: [EnemyKind.strong], count: 8),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 20,
    groups: [
      WaveGroup(sequence: [EnemyKind.medic, EnemyKind.strong], count: 10),
      WaveGroup(sequence: [EnemyKind.strongFast], count: 8),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 15,
    groups: [
      WaveGroup(sequence: [EnemyKind.spawner], count: 1),
      WaveGroup(sequence: [EnemyKind.tank], count: 8),
      WaveGroup(sequence: [EnemyKind.faster], count: 10),
    ],
  ),
  WaveTemplate(
    spawnCooldown: 10,
    groups: [
      WaveGroup(
        sequence: [EnemyKind.taunt, EnemyKind.medic, EnemyKind.tank],
        count: 12,
      ),
      WaveGroup(sequence: [EnemyKind.spawner], count: 2),
    ],
  ),
];

List<WaveTemplate> parseWaveTemplates(List<dynamic>? raw) {
  if (raw == null) {
    return defaultCustomWaves;
  }
  return raw
      .map((dynamic item) {
        final list = item as List<dynamic>;
        final groups = <WaveGroup>[];
        for (var i = 1; i < list.length; i++) {
          final group = list[i] as List<dynamic>;
          final count = group.last as int;
          final sequence = group
              .take(group.length - 1)
              .map((dynamic entry) => enemyKindFromName(entry as String))
              .toList(growable: false);
          groups.add(WaveGroup(sequence: sequence, count: count));
        }
        return WaveTemplate(spawnCooldown: list.first as int, groups: groups);
      })
      .toList(growable: false);
}
